import numpy as np


def interpolant(t):
    return t*t*t*(t*(t*6 - 15) + 10)


def generate_perlin_noise_2d(shape: tuple[int, int], res: tuple[int, int], tileable: tuple[bool, bool] =(False, False), interpolant: callable =interpolant) -> np.ndarray:
    """Generate a 2D numpy array of perlin noise.

    :param tuple[int, int] shape: The shape of the generated array (tuple of two ints). This must be a multple of res.
    :param tuple[int, int] res: The number of periods of noise to generate along each axis. Note shape must be a multiple of res.
    :param tuple[bool, bool] tileable: If the noise should be tileable along each axis (tuple of two bools). Defaults to (False, False).
    :param callable interpolant: The interpolation function, defaults to t*t*t*(t*(t*6 - 15) + 10).
    :return np.ndarray: A numpy array of shape shape with the generated noise.
    """
    delta = (res[0] / shape[0], res[1] / shape[1])
    d = (shape[0] // res[0], shape[1] // res[1])
    grid = np.mgrid[0:res[0]:delta[0], 0:res[1]:delta[1]]\
             .transpose(1, 2, 0) % 1
    # Gradients
    angles = 2*np.pi*np.random.rand(res[0]+1, res[1]+1)
    gradients = np.dstack((np.cos(angles), np.sin(angles)))
    if tileable[0]:
        gradients[-1,:] = gradients[0,:]
    if tileable[1]:
        gradients[:,-1] = gradients[:,0]
    gradients = gradients.repeat(d[0], 0).repeat(d[1], 1)
    g00 = gradients[    :-d[0],    :-d[1]]
    g10 = gradients[d[0]:     ,    :-d[1]]
    g01 = gradients[    :-d[0],d[1]:     ]
    g11 = gradients[d[0]:     ,d[1]:     ]
    # Ramps
    n00 = np.sum(np.dstack((grid[:,:,0]  , grid[:,:,1]  )) * g00, 2)
    n10 = np.sum(np.dstack((grid[:,:,0]-1, grid[:,:,1]  )) * g10, 2)
    n01 = np.sum(np.dstack((grid[:,:,0]  , grid[:,:,1]-1)) * g01, 2)
    n11 = np.sum(np.dstack((grid[:,:,0]-1, grid[:,:,1]-1)) * g11, 2)
    # Interpolation
    t = interpolant(grid)
    n0 = n00*(1-t[:,:,0]) + t[:,:,0]*n10
    n1 = n01*(1-t[:,:,0]) + t[:,:,0]*n11
    return np.sqrt(2)*((1-t[:,:,1])*n0 + t[:,:,1]*n1)


def generate_fractal_noise_2d(
    shape: tuple[int, int], res: tuple[int, int], octaves: int = 1,
    persistence: float = 0.5, lacunarity: int = 2,
    tileable: tuple[bool, bool] = (False, False),
    interpolant: callable = interpolant
) -> np.ndarray:
    """Generate a 2D numpy array of fractal noise.

    :param tuple[int, int] shape: The shape of the generated array. This must be a multiple of lacunarity**(octaves-1)*res.
    :param tuple[int, int] res: The number of periods of noise to generate along each axis. Note shape must be a multiple of (lacunarity**(octaves-1)*res).
    :param int octaves: The number of octaves in the noise. Defaults to 1.
    :param float persistence: The scaling factor between two octaves.
    :param int lacunarity: The frequency factor between two octaves.
    :param tuple[bool, bool] tileable: If the noise should be tileable along each axis. Defaults to (False, False).
    :param callable interpolant: The interpolation function, defaults to t*t*t*(t*(t*6 - 15) + 10).
    :return np.ndarray: A numpy array of fractal noise and of shape shape generated by combining several octaves of perlin noise.
    """
    noise = np.zeros(shape)
    frequency = 1
    amplitude = 1
    for _ in range(octaves):
        noise += amplitude * generate_perlin_noise_2d(
            shape, (frequency*res[0], frequency*res[1]), tileable, interpolant
        )
        frequency *= lacunarity
        amplitude *= persistence
    return noise